model:
  gp_model_str: "exact_gp"
  discount_factor: 0.9999
  batch_size: 32
  replay_buffer_size: 64
  exploring_starts: 100
  max_dataset_size: 2000
  sparsification_threshold: None
  gp_likelihood_noise_constraint: None
  kernel_type: "rbf"
  strategy: 'thompson_sampling'

  # Below is not used yet.
  # Probably not use at all, kernel parameters are
  # fitted to the data anyway.
  kernel:
    matern_kernel:
      smoothness: 2.5   # mu
      outputscale_constraint:
        lower: None
        upper: None
        use_default: True

    rbf_kernel:
      lengthscale_constraint: # default is 0.6931
        lower: None
        upper: None
        use_default: True
      outputscale_constraint:
        lower: None
        upper: None
        use_default: True

    rff_kernel:
      num_samples: 1024
      outputscale_constraint:
        lower: None
        upper: None
        use_default: True


