dgp_hidden_layers_config:
  - output_dims: null
    mean_type: constant

fitting:
  gp_fit_num_epochs: 4
  gp_fit_batch_size: 64
  gp_fit_num_batches: 15
  gp_fit_learning_rate: 0.005
  gp_fit_random_batching: True

exploration:    # Not used if thompson sampling is used.
  ucb_beta: 1.5
  gp_e_greedy_steps: 3500

model:
  gp_model_str: "deep_gp"
  discount_factor: 0.99
  batch_size: 32
  replay_buffer_size: 32
  exploring_starts: 0
  max_dataset_size: 10000
  sparsification_threshold: None
  gp_likelihood_noise_constraint: None
  kernel_type: "matern"
  strategy: "thompson_sampling"
  posterior_observation_noise: False
  num_inducing_points: 512    # Only has effect if variational GP or deep GP is selected.



  kernel:
    matern_kernel:
      smoothness: 2.5   # mu
      outputscale_constraint:
        lower: None
        upper: None
        use_default: True

    rbf_kernel:
      lengthscale_constraint: # default is 0.6931
        lower: None
        upper: None
        use_default: True
      outputscale_constraint:
        lower: None
        upper: None
        use_default: True

    rff_kernel:
      num_samples: 1024
      outputscale_constraint:
        lower: None
        upper: None
        use_default: True