version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "8888:8888"    # Prob not necessary
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - .:/app
    # https://docs.docker.com/compose/gpu-support/\
    deploy:           # Ensure docker container can "see" gpu
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]