model:
  gp_model_str: "variational_gp"
  discount_factor: 0.99
  batch_size: 32
  replay_buffer_size: 64
  exploring_starts: 100
  max_dataset_size: 3000
  sparsification_threshold: None
  gp_likelihood_noise_constraint: None
  kernel_type: "rbf"
  strategy: "upper_confidence_bound"
  posterior_observation_noise: False
  num_inducing_points: 1024    # Only has effect if variational GP or deep GP is selected.

  kernel:
    matern_kernel:
      smoothness: 2.5   # mu
      outputscale_constraint:
        lower: None
        upper: None
        use_default: True

    rbf_kernel:
      lengthscale_constraint: # default is 0.6931
        lower: None
        upper: None
        use_default: True
      outputscale_constraint:
        lower: None
        upper: None
        use_default: True

    rff_kernel:
      num_samples: 1024
      outputscale_constraint:
        lower: None
        upper: None
        use_default: True