model:
  model_type: "linear"
  discount_factor: 0.99
  learning_rate: !!float 2.3e-3
  batch_size: 64
  replay_buffer_size: 128
  exploring_starts: 500
  max_dataset_size: 5000
  annealing_num_steps: 3000
  gradient_steps: 4

training:
  n_timesteps: !!float 5e4